#server:
#  shutdown: graceful
spring:

  main:
    allow-circular-references: true
    web-application-type: SERVLET
  jpa:
    database: default
    generate-ddl: false
    properties:
      hibernate:
        cache.use_second_level_cache: false
        generate_statistics: false
        default_schema: public
        format_sql: true
        ddl-auto: none
    show-sql: ${SHOW_SQL:false}
  liquibase:
   change-log: classpath:db/changelog/db.changelog-master.yml
   default-schema: public
  datasource:
    hikari:
      maximum-pool-size: 15
      connection-timeout: 10000
      initialization-fail-timeout: 60000
      register-mbeans: true
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://postgres:5432/bakery_shop}   # fallback not localhost
    username: ${DATABASE_USER:bakery}
    password: ${DATABASE_PASSWORD:"N&LBAKERY"}
#  profiles:
#    active: local

#  docker:
#    compose:
#      file: bakery-docker/locally/docker-compose-base.yml
#  cors:
#    allowed-origins: "http://localhost:4200"
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probe:
        enabled: true
      show-details: never
