services:

  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: bakery
      POSTGRES_PASSWORD: N&LBAKERY
      POSTGRES_DB: bakery_shop
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - springnet



volumes:
  pgdata:

networks:
  springnet: {}
