name: Continuous Integration/Deployment

on:
  push:
    branches: [ "master" ]
    paths:
      - "src/**"
      - "backery-docker/**"
  pull_request:
    branches: [ "master" ]
    paths:
      - "src/**"
      - "backery-docker/**"
  workflow_dispatch:
    inputs:
      sync:
        description: "File synchronization"
        required: true
        default: "delta"
jobs:
  ci:
    uses: blou5/continu-integ-deve/.github/workflows/api-ci-gradle.yml@task-1/remove-deploy
    secrets:
      git_token: ${{ secrets.GITHUB_TOKEN }}
      sonar_token: ${{ secrets.SONAR_TOKEN }}

  cd-dev:
    needs: ci
    #    if: github.event_name  == 'push'
    uses: blou5/continu-integ-deve/.github/workflows/common-cd.yml@task-1/remove-deploy
    with:
      environment: dev
      docker-file-path: "Dockerfile"
      tag: "buziul/bakery-api:latest"
      local-path: "bakery-docker/dev"
      remote-path: "/home/bakery/api"
      artifact-path: "build/libs"
      deploy-script: "
              cd /home/bakery/api &&
               docker compose pull &&
              docker compose up -d"
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      HOST: ${{secrets.HOST}}
      SSH_USER: ${{secrets.SSH_USER}}
      SSH_PRIVATE_KEY: ${{secrets.SSH_PRIVATE_KEY}}